version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
  webdriver_chrome:
    image: selenium/standalone-chrome
  web:
    build: .
    volumes:
      - .:/pizza_app
    ports:
      - "3000:3000"
    environment:
      - SELENIUM_REMOTE_HOST=webdriver_chrome
    depends_on:
      - db
      - webdriver_chrome
volumes:
  postgres:
