default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_pizza_challange_development

test:
  <<: *default
  database: rails_pizza_challange_test

production:
  <<: *default
  database: rails_pizza_challange_production
  username: rails_pizza_challange
  password: <%= ENV["RAILS_PIZZA_CHALLANGE_DATABASE_PASSWORD"] %>
